name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install, lint, build
      run: |
        yarn install
        npx tslint --project tsconfig.json
        yarn dist
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: dist
        path: dsit.zip
